name: multiple-worklfow

on:
    push

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout REPO
          uses: actions/checkout@v4
        
        - name: install cowsay program
          run: sudo apt-get install cowsay -y

    test_job:
        runs-on: ubuntu-latest
        steps:
        - name: Execute cowsay
          run: cowsay -f dragon "Run for cover, I m dragon " >> dragon.txt  
    
    deploy_job:
        runs-on: ubuntu-latest
        steps:
        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

        - name: read File
          run: cat dragon.txt

        - name: List repo files
          run: ls -ltra
