name: First-workflow

on:
    push

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout REPO
          uses: actions/checkout@v4
        
        - name: list and read repo
          run: |
            echo "My first double workflow"
            ls - ltra
            cat README.MD

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I m dragon " >> dragon.txt  
